source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AlamofireRSSParser_Example', :exclusive => true do
  pod 'AlamofireRSSParser', :path => '../'
end

target 'AlamofireRSSParser_Tests', :exclusive => true do
  pod 'AlamofireRSSParser', :path => '../'

  
end
